" Vim syntax file for ABNF grammars (auto-generated by zpars)
" Language: ABNF

if exists('b:current_syntax')
  finish
endif

syn match abnfRulename /\<[a-zA-Z][a-zA-Z0-9-]*\>/
syn match abnfOperator /[=\/\*()\[\]]/
syn match abnfOperator /=\//
syn region abnfString start=/"/ end=/"/
syn match abnfString /%[si]"[^"]*"/
syn region abnfProse start=/</ end=/>/
syn match abnfNumber /%b[01][01.\-]*/
syn match abnfNumber /%d[0-9][0-9.\-]*/
syn match abnfNumber /%x[0-9A-Fa-f][0-9A-Fa-f.\-]*/
syn match abnfNumber /\<[0-9]\+\>/
syn match abnfComment /;.*$/

hi def link abnfRulename Type
hi def link abnfOperator Operator
hi def link abnfString String
hi def link abnfProse String
hi def link abnfNumber Number
hi def link abnfComment Comment

let b:current_syntax = 'abnf'
