" Vim syntax file for BNF grammars (auto-generated by zpars)
" Language: BNF

if exists('b:current_syntax')
  finish
endif

syn region bnfRulename start=/</ end=/>/
syn match bnfOperator /::=/
syn match bnfOperator /|/

hi def link bnfRulename Type
hi def link bnfOperator Operator

let b:current_syntax = 'bnf'
