" Vim syntax file for CFG grammars (auto-generated by zpars)
" Language: CFG

if exists('b:current_syntax')
  finish
endif

syn match cfgIdentifier /\<[a-zA-Z_][a-zA-Z0-9_-]*\>/
syn match cfgOperator /->/
syn match cfgOperator /|/
syn region cfgString start=/"/ end=/"/
syn match cfgString /%[si]"[^"]*"/
syn match cfgNumber /%x[0-9A-Fa-f]\+\(-[0-9A-Fa-f]\+\)\=/
syn match cfgComment /\/\/.*$/

hi def link cfgIdentifier Type
hi def link cfgOperator Operator
hi def link cfgString String
hi def link cfgNumber Number
hi def link cfgComment Comment

let b:current_syntax = 'cfg'
