" Vim syntax file for PEG grammars (auto-generated by zpars)
" Language: PEG

if exists('b:current_syntax')
  finish
endif

syn match pegIdentifier /\<[a-zA-Z_][a-zA-Z0-9_]*\>/
syn match pegOperator /<-/
syn match pegOperator /[\/&!?*+.]/
syn region pegString start=/'/ end=/'/ skip=/\\./
syn region pegString start=/"/ end=/"/ skip=/\\./
syn region pegCharClass start=/\[/ end=/\]/ skip=/\\./
syn match pegComment /#.*$/

hi def link pegIdentifier Type
hi def link pegOperator Operator
hi def link pegString String
hi def link pegComment Comment
hi def link pegCharClass Special

let b:current_syntax = 'peg'
