//! Vim syntax file generator for zpars grammar formats.
//!
//! Generates `abnf.vim`, `bnf.vim`, `peg.vim`, and `cfg.vim` syntax files
//! based on the same token patterns used by the scanners. Output directory
//! is taken from argv or defaults to `editors/vim/syntax/`.

const std = @import("std");

const Io = std.Io;

const Language = struct {
    name: []const u8,
    display: []const u8,
    rules: []const Rule,
};

const Rule = struct {
    group: []const u8,
    kind: Kind,

    const Kind = union(enum) {
        match: []const u8,
        region: Region,
    };

    const Region = struct {
        start: []const u8,
        end: []const u8,
        skip: ?[]const u8 = null,
    };
};

const abnf_rules = [_]Rule{
    .{ .group = "abnfRulename", .kind = .{ .match = "\\<[a-zA-Z][a-zA-Z0-9-]*\\>" } },
    .{ .group = "abnfOperator", .kind = .{ .match = "[=/\\*()\\[\\]]" } },
    .{ .group = "abnfOperator", .kind = .{ .match = "=/" } },
    .{ .group = "abnfString", .kind = .{ .region = .{ .start = "\"", .end = "\"" } } },
    .{ .group = "abnfString", .kind = .{ .match = "%[si]\"[^\"]*\"" } },
    .{ .group = "abnfProse", .kind = .{ .region = .{ .start = "<", .end = ">" } } },
    .{ .group = "abnfNumber", .kind = .{ .match = "%b[01][01.\\-]*" } },
    .{ .group = "abnfNumber", .kind = .{ .match = "%d[0-9][0-9.\\-]*" } },
    .{ .group = "abnfNumber", .kind = .{ .match = "%x[0-9A-Fa-f][0-9A-Fa-f.\\-]*" } },
    .{ .group = "abnfNumber", .kind = .{ .match = "\\<[0-9]\\+\\>" } },
    .{ .group = "abnfComment", .kind = .{ .match = ";.*$" } },
};

const bnf_rules = [_]Rule{
    .{ .group = "bnfRulename", .kind = .{ .region = .{ .start = "<", .end = ">" } } },
    .{ .group = "bnfOperator", .kind = .{ .match = "::=" } },
    .{ .group = "bnfOperator", .kind = .{ .match = "|" } },
};

const peg_rules = [_]Rule{
    .{ .group = "pegIdentifier", .kind = .{ .match = "\\<[a-zA-Z_][a-zA-Z0-9_]*\\>" } },
    .{ .group = "pegOperator", .kind = .{ .match = "<-" } },
    .{ .group = "pegOperator", .kind = .{ .match = "[/&!?*+.]" } },
    .{ .group = "pegString", .kind = .{ .region = .{ .start = "'", .end = "'", .skip = "\\\\." } } },
    .{ .group = "pegString", .kind = .{ .region = .{ .start = "\"", .end = "\"", .skip = "\\\\." } } },
    .{ .group = "pegCharClass", .kind = .{ .region = .{ .start = "\\[", .end = "\\]", .skip = "\\\\." } } },
    .{ .group = "pegComment", .kind = .{ .match = "#.*$" } },
};

const cfg_rules = [_]Rule{
    .{ .group = "cfgIdentifier", .kind = .{ .match = "\\<[a-zA-Z_][a-zA-Z0-9_-]*\\>" } },
    .{ .group = "cfgOperator", .kind = .{ .match = "->" } },
    .{ .group = "cfgOperator", .kind = .{ .match = "|" } },
    .{ .group = "cfgString", .kind = .{ .region = .{ .start = "\"", .end = "\"" } } },
    .{ .group = "cfgString", .kind = .{ .match = "%[si]\"[^\"]*\"" } },
    .{ .group = "cfgNumber", .kind = .{ .match = "%x[0-9A-Fa-f]\\+\\(-[0-9A-Fa-f]\\+\\)\\=" } },
    .{ .group = "cfgComment", .kind = .{ .match = "//.*$" } },
};

const languages = [_]Language{
    .{ .name = "abnf", .display = "ABNF", .rules = &abnf_rules },
    .{ .name = "bnf", .display = "BNF", .rules = &bnf_rules },
    .{ .name = "peg", .display = "PEG", .rules = &peg_rules },
    .{ .name = "cfg", .display = "CFG", .rules = &cfg_rules },
};

const hi_links = [_]struct { suffix: []const u8, target: []const u8 }{
    .{ .suffix = "Rulename", .target = "Type" },
    .{ .suffix = "Identifier", .target = "Type" },
    .{ .suffix = "Operator", .target = "Operator" },
    .{ .suffix = "String", .target = "String" },
    .{ .suffix = "Prose", .target = "String" },
    .{ .suffix = "Number", .target = "Number" },
    .{ .suffix = "Comment", .target = "Comment" },
    .{ .suffix = "CharClass", .target = "Special" },
};

fn writePattern(w: *Io.Writer, pat: []const u8) !void {
    for (pat) |c| {
        if (c == '/') {
            try w.writeAll("\\/");
        } else {
            try w.writeByte(c);
        }
    }
}

fn generate(io: Io, lang: Language, dir: Io.Dir) !void {
    var name_buf: [64]u8 = undefined;
    const filename = std.fmt.bufPrint(&name_buf, "{s}.vim", .{lang.name}) catch unreachable;

    const file = try dir.createFile(io, filename, .{});
    defer file.close(io);

    var buf: [4096]u8 = undefined;
    var fw = file.writer(io, &buf);
    const w = &fw.interface;

    try w.writeAll("\" Vim syntax file for ");
    try w.writeAll(lang.display);
    try w.writeAll(" grammars (auto-generated by zpars)\n\" Language: ");
    try w.writeAll(lang.display);
    try w.writeAll("\n\nif exists('b:current_syntax')\n  finish\nendif\n\n");

    for (lang.rules) |rule| {
        switch (rule.kind) {
            .match => |pat| {
                try w.writeAll("syn match ");
                try w.writeAll(rule.group);
                try w.writeAll(" /");
                try writePattern(w, pat);
                try w.writeAll("/\n");
            },
            .region => |reg| {
                try w.writeAll("syn region ");
                try w.writeAll(rule.group);
                try w.writeAll(" start=/");
                try writePattern(w, reg.start);
                try w.writeAll("/ end=/");
                try writePattern(w, reg.end);
                try w.writeAll("/");
                if (reg.skip) |skip| {
                    try w.writeAll(" skip=/");
                    try writePattern(w, skip);
                    try w.writeAll("/");
                }
                try w.writeAll("\n");
            },
        }
    }

    try w.writeAll("\n");

    for (hi_links) |link| {
        for (lang.rules) |rule| {
            if (std.mem.endsWith(u8, rule.group, link.suffix)) {
                try w.writeAll("hi def link ");
                try w.writeAll(rule.group);
                try w.writeAll(" ");
                try w.writeAll(link.target);
                try w.writeAll("\n");
                break;
            }
        }
    }

    try w.writeAll("\nlet b:current_syntax = '");
    try w.writeAll(lang.name);
    try w.writeAll("'\n");

    try w.flush();
}

pub fn main(init: std.process.Init) !void {
    const io = init.io;

    var args = init.minimal.args.iterate();
    _ = args.next(); // skip program name

    const out_path = args.next() orelse "editors/vim/syntax";

    var dir = Io.Dir.cwd().createDirPathOpen(io, out_path, .{}) catch |err| {
        std.debug.print("cannot open output directory '{s}': {}\n", .{ out_path, err });
        std.process.exit(1);
    };
    defer dir.close(io);

    for (&languages) |lang| {
        generate(io, lang, dir) catch |err| {
            std.debug.print("failed to generate {s}.vim: {}\n", .{ lang.name, err });
            std.process.exit(1);
        };
    }
}
